[build]
  command = "astro build"
  publish = "dist"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/js/site-metrics.js"
  to = "https://plausible.io/js/pa-Cr0W9evv4_OrXNX6b_4Zk.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/site-metrics"
  to = "https://plausible.io/api/event"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"
